Update realease_package.yml

diff --git a/.github/workflows/realease_package.yml b/.github/workflows/realease_package.yml
--- a/.github/workflows/realease_package.yml
+++ b/.github/workflows/realease_package.yml
@@ -28,21 +28,27 @@ jobs:
         with:
           name: python-package
           path: dist
-          repository: ${{ github.repository }}
-          github-token: ${{ github.token }}
-          run-id: ${{ github.event.workflow_run.id }}
-
-
 
       - name: List directory contents
         run: ls -la dist/
         shell: bash
 
+      - name: Ensure Cloudsmith CLI is installed
+        run: |
+          if ! command -v cloudsmith &> /dev/null; then
+            echo "Cloudsmith CLI not found! Installing..."
+            curl -1sLf 'https://dl.cloudsmith.io/public/cloudsmith/cli/setup.sh' | bash
+            sudo apt-get install -y cloudsmith-cli
+          fi
+          cloudsmith --version
+        shell: bash
+
       - name: Push package to Cloudsmith
         run: |
-          if ! ls dist/*.tar.gz 1> /dev/null 2>&1; then
+          PACKAGE_FOUND=$(ls dist/*.tar.gz dist/*.whl 2>/dev/null | wc -l)
+          if [ "$PACKAGE_FOUND" -eq "0" ]; then
             echo "No package found to upload"
             exit 1
           fi
-          cloudsmith push python ${{ env.CLOUDSMITH_NAMESPACE }}/${{ env.CLOUDSMITH_REPOSITORY }} dist/*.tar.gz --republish
-        shell: bash
+
+          for FILE i
